cmake_minimum_required(VERSION 3.29)
project(CodeForces)

set(CMAKE_CXX_STANDARD 14)

add_executable(CodeForces
    cses/1.cpp
    cses/2.cpp
    cses/cc2.cpp
    cses/cses4.cpp
    1.cpp
    2.cpp
    9651.cpp
    9653.cpp
    9671.cpp
    9672.cpp
    9681.cpp
    9682.cpp
    9683.cpp
    cf.cpp
    cf1.cpp
    cf2.cpp
    cf3.cpp
    code.cpp
    cses1.cpp
    cses2.cpp
    cses3.cpp
    main.cpp
    p1.cpp)
